version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    command: >
      sh -c "ollama pull llama3.2:1b && ollama serve"
    networks:
      - shared_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama
    networks:
      - shared_network

networks:
  shared_network:
    driver: bridge
